---
- hosts: webserver 
  sudo: yes

  vars:
    http_port: 80

  tasks:

    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - git

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: clone basic html template
      git: repo=https://github.com/ShaliniMNarang/EntSWPlatforms.git dest=/var/www/html/EntSWPlatforms update=yes force=yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
